### ISSUE TITLE
Error in curl

### ISSUE THREAD

**Issue by wsn19930220** [ropensci/smapr#68] opened 2021-04-08 11:19 UTC
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [urs.earthdata.nasa.gov] Connection timed out after 10000 milliseconds

**Comment by mbjoseph** [comment] 2021-04-08 21:23
Hi @wsn19930220 - can you please make a reprex: https://reprex.tidyverse.org/ and paste your session information in this issue?

**Comment by mbjoseph** [comment] 2023-03-06 21:17
Closing this for now - can't reproduce.

**Closed by mbjoseph** 2023-03-06 21:17 UTC
