### ISSUE TITLE
Need a suggestion

### ISSUE THREAD

**Issue by nithya255** [ropensci/smapr#65] opened 2020-08-17 12:35 UTC
I used your code for downloading the data but while extracting the downloaded data, the file size is exceeding. Can you please give me suggestion regarding the extraction of the downloaded data.
![image](https://user-images.githubusercontent.com/25099847/90396493-ee4ccd80-e0b3-11ea-931b-0f0aa5315b65.png)
if you are unable to view the above link, you can refer to the link below
[git.docx](https://github.com/ropensci/smapr/files/5084176/git.docx)
Please reply as soon as possible

**Comment by mbjoseph** [comment] 2020-08-17 21:05
Hi @nithya255 - first I'd recommend that you change your Earthdata password, since it's now public. 

I cannot reproduce the error, but sometimes when I've seen that error it's because you've exhausted all of the RAM. If you monitor your RAM usage when trying to extract the data, does it seem like you're getting close to 100% usage?

**Comment by nithya255** [comment] 2020-08-18 05:21
Thanks for your reply. I have gone through your comments and implementing it but the RAM usage while extracting data is not reaching 100% and the limit of the R is 4gb might be the file size of the data is high or exceeds the space allocated for R.

**Comment by mbjoseph** [comment] 2020-08-27 21:15
Sorry this problem is persisting @nithya255 - I'm going to close this issue as I can't reproduce the problem.

**Closed by mbjoseph** 2020-08-27 21:15 UTC
