### ISSUE TITLE
SEC certification issues preventing data download using smapr

### ISSUE THREAD

**Issue by Vinit-Sehgal** [ropensci/smapr#75] opened 2023-03-02 16:05 UTC
Since very recently smapr::find_smap has been throwing an error related to the expiration of the SEC certification:
######
Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_CERT_EXPIRED (0x80090328) - The received certificate has expired.
######
This prevents automated data retrieval using smapr. Is there a way we can circumvent this issue?

**Comment by Vinit-Sehgal** [comment] 2023-03-02 16:26
For those facing the same issue. the error can be circumvented by setting the following config in httr: 
library (httr)
 httr::set_config(config(ssl_verifypeer = 0L, ssl_verifyhost = 0L))

**Comment by mbjoseph** [comment] 2023-03-02 17:11
Thanks for flagging @Vinit-Sehgal -- looks like this is an issue with NSIDC, rather than smapr. I'm seeing something similar when trying to get to the http data site in a web browser (https://n5eil01u.ecs.nsidc.org/SMAP/SPL3SMP.008/). 

I appreciate you providing a fix here. It might be worth letting the folks at NSIDC know that this is an issue so they can fix it on their end.

**Comment by mbjoseph** [comment] 2023-03-06 21:14
Closing this for now, as I'm unable to reproduce.

**Closed by mbjoseph** 2023-03-06 21:14 UTC
